global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'my-java-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['my-java-app:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
