name: Terraform CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: ${{ secrets.TF_VAR_aws_region }}
      TF_VAR_aws_profile: ${{ secrets.TF_VAR_aws_profile }}
      TF_VAR_ami_id: ${{ secrets.TF_VAR_ami_id }}
      TF_VAR_instance_type: ${{ secrets.TF_VAR_instance_type }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH private key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ./id_rsa
          chmod 600 ./id_rsa

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=plan.out
          terraform show -json plan.out > plan.json

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/plan.out

      - name: Check if there are changes
        id: check_changes
        run: |
          changes=$(jq '.resource_changes | length' plan.json)
          echo "changes=$changes" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        if: steps.check_changes.outputs.changes != '0'
        run: terraform apply -auto-approve plan.out
